### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by quasar1** [dersphere/plugin.video.disclose_tv#1]
Just thought I'd report this issue which started yesterday. I have tested on various platforms and XBMC/Kodi versions and they all give the same error. I think it may be to do with the actual disclose.tv website changes. Hopefully it's fixable.

http://xbmclogs.com/show.php?id=422942

Thanks.

**Comment by dersphere** [comment]
Hi,

the add-on was broken due to website changes.

I fixed the add-on and uploaded the fixed version (0.1.0) you should receive an update shortly.
