### ISSUE TITLE
Script Error on plugin 1.2

### ISSUE THREAD

**Issue by genniecommands** [dersphere/plugin.video.disclose_tv#5]
Running Kodi 14.2 on mac os 10.9.5
disclose.tv 0.1.2 was working but day before not showing thumbnails
then the day later script error on play, All list seem to populate and update.

Kodi Log Uploader ID:p12j73dwr  at http:xbmclogs/p12j73dwr
user udsonline@me.com

Thank you for your contribution I use it every week
Martyn Ford

**Comment by dersphere** [comment]
Fixed
